version: '3.8'

services:
  ball-game:
    build: .
    image: ball-game
    container_name: ball-game
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - SDL_VIDEODRIVER=x11
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
    restart: "no"

